Adding model vendor support
validmind/documentation pull request #205
Opened 2024-05-28 21:35 UTC by noosheenv

## Internal Notes for Reviewers

### I added steps to `guide/register-models-in-model-inventory.qmd` to document the new feature:

| Before | After |
| ----- | ----- |
| <img width="668" alt="image" src="https://github.com/validmind/documentation/assets/143854391/a2edd1bd-8ca4-4bf9-8d61-1ac34575e799"> | <img width="788" alt="image" src="https://github.com/validmind/documentation/assets/143854391/f510ca70-295c-4cff-98a6-0068da41d6f9"> |

### I added the term "model vendor" to the glossary:
<img width="670" alt="image" src="https://github.com/validmind/documentation/assets/143854391/7dbb2a5c-8305-40d9-a447-2a0ee6b85550">

*Should we also add "vendor model"

### I added a callout in `guide/supported-models.qmd` under "Supported model types" to show that we support vendor models:
<img width="966" alt="image" src="https://github.com/validmind/documentation/assets/143854391/2ade45d4-3266-427e-9e08-32cb1df26cb7">

## External Release Notes

2024-05-28 22:00 UTC, validbeck requested changes
> *Should we also add "vendor model"

- Yes, and make sure it's a **span with an ID** so we can link to the anchor on the page! 
- You'll need to dig into your HTML knowledge here, or take a look at the code showcased in the examples for help ;) (I noticed that the link below is actually broken, it should be `https://docs.validmind.ai/about/glossary/glossary.html#platform-model-inventory` in full, so you'll want to fix that while you're there as well!

| Example anchor link | Example span ID |
|---|---|
|<img width="294" alt="Screenshot 2024-05-28 at 2 54 43 PM" src="https://github.com/validmind/documentation/assets/164545837/2c561289-278b-4fa0-be42-92faf4c9b769">|![Screenshot 2024-05-28 at 2 55 07 PM](https://github.com/validmind/documentation/assets/164545837/5ce5f4e6-d6b2-4f6e-af91-831b4ee84bdc)|

> I added steps to guide/register-models-in-model-inventory.qmd to document the new feature

I'd make the first `vendor model` a link to your anchor once it's available.

> I added a callout in guide/supported-models.qmd under "Supported model types" to show that we support vendor models

I'd make `third-party vendor models` a link to the anchor here as well once it's available.

2024-05-28 22:59 UTC, validbeck commented
@noosheenv 

> The two spots that link to vendor-model won't work until it's deployed on prod because it's linking to the website instead of a file, hope that's okay!

You can spot check it in the static rendered `_site` files ;)

2024-05-28 23:57 UTC, validbeck commented
@noosheenv I just took a look at your files, and I see what you meant by not being able to double-check the links. The format should actually follow the "good" structure, i.e. (instead of linking out to the live website):

```
../../about/glossary/glossary.html#platform-model-inventory
```

Are you able to adjust the links you added to the above, and that way you can double-check and make sure the spans work? I also noticed your formatting for the spans is a little wonky, and I'm not sure they will perform in the same way with your spacing/wrapping of the text. Can you adjust them to look like the following:

```
model inventory <span id="platform-model-inventory">
```

2024-05-29 16:36 UTC, nrichers reviewed
Left a couple of suggestions to use relative links.

2024-05-29 16:36 UTC, nrichers commented on site/guide/register-models-in-model-inventory.qmd
> +   - If the model is a [vendor model](https://docs.validmind.ai/about/glossary/glossary.html#vendor-model), toggle **Is Vendor Model** and provide the vendor name.
```suggestion
   - If the model is a [vendor model](../about/glossary/glossary.qmd#vendor-model), toggle **Is Vendor Model** and provide the vendor name.
```

Use a relative link. This works, I tested it, though we do have an issue with the navbar at the top covering the text.

2024-05-29 16:36 UTC, nrichers commented on site/guide/supported-models.qmd
> +ValidMind offers support for both first-party models and [third-party vendor models](https://docs.validmind.ai/about/glossary/glossary.html#vendor-model).
```suggestion
ValidMind offers support for both first-party models and [third-party vendor models](../about/glossary/glossary.qmd#vendor-model).
```

2024-05-29 17:16 UTC, validbeck approved these changes
@nrichers I'm observing the same behaviour as when I last worked with the Glossary, see sc-4381. Otherwise it more or less works as expected!

2024-05-29 17:17 UTC, merged