Release notes to sprint 55
validmind/documentation pull request #270
Opened 2024-08-09 17:05 UTC by noosheenv

## Internal Notes for Reviewers
I did some release notes!
This was generated using the notebook in another branch, so I copied the files over to this branch.
You can find this in `~/site/releases/2024-aug-13`

<img width="1191" alt="image" src="https://github.com/user-attachments/assets/c4a48ba0-9f0f-4ccb-9235-a751e453b523">

## External Release Notes

2024-08-09 21:31 UTC, validbeck requested changes
Nice work pulling these together!

- Right under the `Release highlights` heading, you need to summarize the whole release in 250 characters or less. ;) (They will eventually get pulled into [a yearly releases](https://docs.validmind.ai/releases/2023/2023-releases.html), which uses our listings...)
- It looks like you didn't manage to adjust the columns to actually stack side-by-side for some of these, so give that another go. 
- Some of the wording needs a visit from the grammar fairy (as Nik calls it). For example, "You need" > `You'll need` etc. There are some incomplete sentences without punctuation as well.

2024-08-09 22:36 UTC, noosheenv commented
Thanks for the feedback! Here are my edits:
Oh my god the column thing wasn't working because I didn't add `filters: tachyons` to the frontmatter 🙄 silly me.
For the summary, I just followed the vibe of the March 27, 2024 release, because the newer ones don't have one.
Grammar hopefully fixed now!

2024-08-13 18:03 UTC, validbeck commented
> @noosheenv I can't approve this PR unless you re-request review. ;)

Either way, here are some changes I made that you should take note of:

- Updated the summary for the release missing the summary ([July 22, 2024](https://github.com/validmind/documentation/pull/270/files#diff-617fe0359dc0485790d9c5371da5ce4b4fc1f191b55241741fe3b508e7e7d8a9)) & added both newer releases to [`2024-releases.qmd`](https://github.com/validmind/documentation/pull/270/files#diff-eca483287241ec0799f03f6cdf00966a711cb500270b5e39ac23b1dffaf0ed32) (Remember the scout philosophy of leaving things better than you found them?)
- For Aug 13, 2024: 
  - Adjusted the layout of some sections to be a bit more streamlined
  - Edited text for accuracy clarity and **context** (this is important!!)
  - Removed the period at the end of alt text (general style convention — unless it is a complete sentence, no punctuation is needed for UI elements) 

| Old | New | Details |
|---|---|---|
|<img width="1159" alt="Screenshot 2024-08-13 at 10 48 17 AM" src="https://github.com/user-attachments/assets/6ffbcc94-1425-42ea-8d28-09c406d434f8"> | <img width="1171" alt="Screenshot 2024-08-13 at 10 43 52 AM" src="https://github.com/user-attachments/assets/e039273f-3890-4722-83f4-ead6768550ca"> | Summaries need to both be more broad and more descriptive. **Context is important — Make sure you refer to UI elements users can interact with for reference, and provide any supplementary information.** Get rid of the modal verb ("you can") and simply use the imperative ("do [x]"); you're inciting a call to action! When we use columns, they're to enhance the layout, not just to offset items. |
|<img width="1173" alt="Screenshot 2024-08-13 at 10 52 40 AM" src="https://github.com/user-attachments/assets/9605e8fc-c63a-4683-ba9c-288e4db0ed87"> | <img width="1194" alt="Screenshot 2024-08-13 at 10 43 59 AM" src="https://github.com/user-attachments/assets/14f93b73-cfc3-4d2f-843c-754b3872df62">| Again, provide context (links are great). Removed the `important` callout class, [as this isn't a warning](https://docs.validmind.ai/about/contributing/style-guide/conventions.html#callouts) — it's just information. |
|<img width="1186" alt="Screenshot 2024-08-13 at 10 54 39 AM" src="https://github.com/user-attachments/assets/889a2f7e-ff63-49da-9d3d-ecc315674e0e"> | <img width="1200" alt="Screenshot 2024-08-13 at 10 44 06 AM" src="https://github.com/user-attachments/assets/89fe34ef-2993-4b2e-9b0a-7936278e7003">| Make sure when you reference UI elements you follow the casing you see in the UI. **Always include more context — why is this feature relevant or useful to users?** |
| <img width="795" alt="Screenshot 2024-08-13 at 10 56 32 AM" src="https://github.com/user-attachments/assets/fc94ad89-dcd2-48a7-b4cd-2543e1693cb2">|<img width="1190" alt="Screenshot 2024-08-13 at 10 44 16 AM" src="https://github.com/user-attachments/assets/d011984e-e19e-4e2a-a33e-b1b1d871108f"> | Cleanup here for layout. **This section also would have benefitted from you digging into the feature a little to understand what you're describing.** I've made the necessary edits to the filename/descriptions. |
| <img width="1193" alt="Screenshot 2024-08-13 at 10 57 48 AM" src="https://github.com/user-attachments/assets/848f6401-ceac-45f7-86f1-e4d56639809f">| <img width="1173" alt="Screenshot 2024-08-13 at 11 01 13 AM" src="https://github.com/user-attachments/assets/d70da8e5-00f7-4abf-b703-5a52dabeccce"> | **Your bug fix really needed context — what is this referring to (the links) and *why was it important that this bug was fixed?*** Section headers really needed some work too; they should succinctly summarize but not be too wordy. |

> **Note:** When you publish these to `prod` as per the process, make sure you run `make get-source` as we are missing some notebooks that are on the `developer-framework` repo on `main`:
>
>```bash
>WARN: Unable to resolve link target: notebooks/how_to/run_tests/2_run_comparison_tests.ipynb
>```

2024-08-13 18:05 UTC, validbeck approved these changes

2024-08-15 16:25 UTC, merged