Templates for videos
validmind/documentation pull request #415
Opened 2024-09-20 02:07 UTC by nrichers

## Internal Notes for Reviewers

This PR adds a basic reveal.js presentation with slides you can use for video intros. WIP

## External Release Notes

2024-09-24 19:30 UTC, nrichers commented
@validbeck this PR is ready to be approved — I mention it in my standard for community videos that is part of Sprint 59 and should be merged.

2024-09-24 21:51 UTC, validbeck requested changes
Very cool, the only thing is how does one render-preview/load the slides locally? I moved the slides into `site` on my local branch to see it, but is there a better way? Perhaps this could be included in the template instructions?

2024-09-24 23:40 UTC, validbeck approved these changes

2024-09-25 00:47 UTC, nrichers commented
> Very cool, the only thing is how does one render-preview/load the slides locally? I moved the slides into `site` on my local branch to see it, but is there a better way? Perhaps this could be included in the template instructions?

This is really more of a "how do I use Quarto question?" but I added the instructions for how to render the presentation to https://www.notion.so/validmind/Community-Videos-7cdc46a3403940b4acd7a32df63d2f7a?pvs=4#10519127eb12801fa6dbcc7b34cab57d

(TL;DR: cd into the folder where the presentation lives and run `quarto preview index.qmd`.)

2024-09-26 17:52 UTC, merged